main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.16"
author: levkopo
description: A plugin for test configuration cisco ios
commands:
  give_unique_item:
    description: Give unique item for player
  cancel_task:
    description: Cancel current task
  start_task:
    description: Start task for player
