main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.16"
author: levkopo
description: A plugin for test configuration cisco ios
commands:
  get_unique:
    description: Get unique object
    usage: "For a list of commands, type /get_unique help"
